name: auto-merge-on-approval-on-pr-into-prod
on:
  pull_request_review:
    types: [submitted]
    branches:
      - production

env:
  GITHUB_PR_NUMBER: ${{github.event.pull_request.number}}
jobs:
  check_that_pr_is_from_master:
    if: github.event.pull_request.base.ref == 'production'
    runs-on: ubuntu-latest
    steps:
    - name: Check if the pull request is mergeable to production
      run: |
        if [[ "$GITHUB_HEAD_REF" == 'master' ]]; then exit 0; else exit 1; fi;

  check_that_the_pr_is_approved_and_merge:
    if: |
      github.event.review.state == 'approved' &&
      github.event.pull_request.base.ref == 'production'
    runs-on: ubuntu-latest
    steps:
      - name: "Merge Pull Request"
        uses: "actions/github-script@v5"
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            const repository = context.repo

            await github.rest.pulls.merge({
              merge_method: "merge",
              owner: repository.owner,
              pull_number: context.payload.pull_request.number,
              repo: repository.repo,
            })
    needs: check_that_pr_is_from_master
